### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by bernt-matthias** [refgenie/refgenie#168]
On https://refgenomes.databio.org/ I get `Error code: SSL_ERROR_INTERNAL_ERROR_ALERT`

**Comment by nsheff** [comment]
Yes we haven't set up https:// yet on that server.

try: http://refgenomes.databio.org

**Comment by bernt-matthias** [comment]
Thanks for the answer. I remember that I clicked on a link somewhere in the docs (can't recall where) and got to the https page. Maybe there is somewhere a link that does not have the http:// ?

**Comment by nsheff** [comment]
could be. I'll look around.
we'll enable https soon and then the link will work! I'll leave this issue open till we get it sorted out.

**Comment by nsheff** [comment]
btw, are you having trouble pulling assets right now? See #169

**Comment by bernt-matthias** [comment]
I just discovered this project and started reading when I stumbled over this one. Have not tried to pull yet :(
