### ISSUE TITLE
Slow downloads -- refgenie server trouble?

### ISSUE THREAD

**Issue by nsheff** [refgenie/refgenie#169]
Hi @nmagee  -- I'm seeing very slow speeds on refgenie downloads again. Can you check to see if that stale container problem has resurfaced?

**Comment by nmagee** [comment]
Yes - checking now.

**Comment by dbrookeUAB** [comment]
I'm also having super slow download speeds.

**Comment by nsheff** [comment]
Thanks for the report. we're almost finished moving everything over to s3, which will improve this dramatically.

**Comment by nsheff** [comment]
@dbrookeUAB can you give it a try now and see if things are any faster for you?

**Comment by dbrookeUAB** [comment]
Trying now...

**Comment by dbrookeUAB** [comment]
Oooooooh yeah.... that's the stuff.  Went from downloading 100kb/s to 200mb/s. Thanks!!

**Comment by nsheff** [comment]
We're now completely moved over to AWS and speeds should be very fast from here on out. closing this issue.
