### ISSUE TITLE
Rename genome function

### ISSUE THREAD

**Issue by nsheff** [refgenie/refgenie#177]
_Originally posted by @nsheff in https://github.com/databio/refgenie/issues/176#issuecomment-637100938_

We need functionality to rename a genome.

Also, if I rename a genome, when I try to pull, refgenieserver should automatically use the correct genome, regardless of name. Will have to think through but I think this may already happen, as long as we're using asset identifiers.

**Comment by stolarczyk** [comment]
noo.. we we just use the asset-derived checksums to assert relationships correctness after pulling

**Comment by nsheff** [comment]
Ok. I think we were just *discussing* the idea of using digests instead of 'hg38' for genomes, then.
