### ISSUE TITLE
Initializing config params

### ISSUE THREAD

**Issue by nsheff** [refgenie/refgenie#182]
```
refgenie init --help
usage: refgenie init [-h] -c GENOME_CONFIG
                     [-s GENOME_SERVER [GENOME_SERVER ...]]

Initialize a genome configuration.

optional arguments:
  -h, --help            show this help message and exit
  -c GENOME_CONFIG, --genome-config GENOME_CONFIG
                        Path to local genome configuration file. Optional if
                        REFGENIE environment variable is set.
  -s GENOME_SERVER [GENOME_SERVER ...], --genome-server GENOME_SERVER [GENOME_SERVER ...]
                        URL(s) to use for the http://refgenomes.databio.org
                        attribute in config file. Default: genome_servers.
```

it would be nice if we allowed `init` to also handle 
- genome_folder
- genome_archive_folder
- genome_archive_config
- remote url base

anything else?

**Comment by stolarczyk** [comment]
added also `--settings-json` argument, which is an absolute path to a JSON file with key value pairs to initialize the config with. They are overwritten by the itemized settings like `--genome-config` etc.

**Comment by nsheff** [comment]
that's a great idea. maybe we don't even need the individual args if you've enabled the json version... ?
