### ISSUE TITLE
No way to avoid 'large asset' prompt

### ISSUE THREAD

**Issue by nsheff** [refgenie/refgenie#191]
Raised by @natefoo

There's no way to bypass the extra prompt for large assets programatically. `--force` doesn't do it.

```
refgenie pull hg18/star_index --force
Are you sure you want to download this large archive? [y/N]
```

**Comment by stolarczyk** [comment]
`--force` in `refgenie pull` just as in `RefGenConf.pull` approves the existing assets overwriting upfront:

https://github.com/refgenie/refgenconf/blob/a186c54279eb95ea45626c8ae077bcb764b7ee9c/refgenconf/refgenconf.py#L579-L592

The help in refgenie CLI is not specific, so it is misleading. 

Anyway, I agree that we should force everything in this case

**Comment by natefoo** [comment]
I'm essentially trying to "mirror" an unarchived refgenieserver in to [CVMFS](https://cvmfs.readthedocs.io/en/stable/), so I want to use both `--no-overwrite` and whatever option would auto-approve the large asset pull so the process can be restarted after interruption. Right now I'm using this (`$assets_json` is just the content of http://refgenomes.databio.org/v2/assets):

```bash
for genome in $(cat "$assets_json" | jq -r 'keys | .[]'); do
    for _asset in $(cat "$assets_json" | jq -r ".${genome} | .[]"); do
        # remove seek key from asset
        asset="${_asset/.*:/:}"
        base_asset="${asset%:*}"
        tag="${asset#*:}"
        full_asset=$"${genome}/${asset}"
        if [ ! -d "/cvmfs/${REPO}/${genome}/${base_asset}/${tag}" ]; then
            cvmfs_server transaction "$REPO"
            refgenie pull --force --no-overwrite "$full_asset"
            if [ -n "$(ls "$UPPER")" ]; then
                cvmfs_server publish -a "init-${genome}-${asset}" -m "Pull asset ${full_asset}" "$REPO"
            else
                echo "no changes, aborting transaction"
                cvmfs_server abort -f "$REPO"
            fi
        else
            echo "skipping: /cvmfs/${REPO}/${genome}/${base_asset}/${tag} exists"
        fi
    done
done
```

I'm checking the local asset dir myself so that I don't have to open/abort a bunch of empty CVMFS transactions for each seek key, so `--no-overwrite` is probably redundant here, and I guess I should drop `--force` since it doesn't prevent me having to confirm download of large assets as I'd hoped.

**Comment by stolarczyk** [comment]
@natefoo, you can switch to `bugfix` branches of refgenconf and refgenie. With the recent changes you can say:
`refgenie pull --force hg18/star_index` to answer "yes" to both prompts. Let us know if that helps.

**Comment by nsheff** [comment]
The shell script above is basically doing what `--mirror` would do (#27), so once that's implemented within refgenie you wouldn't need to do that. also, if we provided an assets only (no seek keys) endpoint (https://github.com/refgenie/refgenieserver/issues/93), then you wouldn't need to do the  empty CVMFS checks, right?

> Anyway, I agree that we should force everything in this case

Do you think these should be modular options? What if you want to force overwrite, but not download large assets? I don't think I'd just make `--force` do both... An alternative hypothetical -- should we just turn off the large asset check altogether?

I'd either make a separate flag for forcing large assets, or just eliminate the large file check completely.

**Comment by natefoo** [comment]
> also, if we provided an assets only (no seek keys) endpoint ([refgenie/refgenieserver#93](https://github.com/refgenie/refgenieserver/issues/93)), then you wouldn't need to do the empty CVMFS checks, right?

That'd reduce the number of transaction/abort steps, but I still need to open a transaction before calling `refgenie pull` since I don't know beforehand (unless I check) whether the pull will do anything. Maybe a `--dry-run` flag or something to indicate whether it *would* do anything to replace my check on the filesystem? That said, the empty transactions are more of an annoyance than anything important, so it's not a huge deal.

**Comment by stolarczyk** [comment]
> Do you think these should be modular options? What if you want to force overwrite, but not download large assets? I don't think I'd just make --force do both

I did make it modular:

```
  -f, --force           Do not prompt before action, approve upfront.
  -o, --no-overwrite    Do not overwrite if asset exists.
  -l, --no-large        Do not pull archives over 5GB.
```

so to achieve the effect you mentioned:

```
refgenie pull --force --no-large
```
the specific force-related options take precedence over the generic `--force`. To make that clear we should wrap all these in an argument group in the argument parser and add an appropriate description.

**Comment by nsheff** [comment]
Hmm... that's not intuitive to me. So you'd have to force, and then *turn off* some aspect of it? 

Flags are always easiest to understand when they turn one thing on and are independent of other flags. I'd argue for something like:

```
 --force-overwrite    Force overwriting if asset exists.
 --no-overwrite     Do not overwrite if asset exists.
 --force-large        Force pulling archives over 5GB.
 --no-large            Do not pull archives over 5GB.
 -- force                Combination of --force-overwrite and --force-large
```

or

```
 --overwrite [y/n]   Auto-respond Y/N to overwrite if asset exists.
 --pull-large [y/n]   Auto-respond Y/N to pull archives over 5GB.
 -- force                Combination of  --overwrite y and --pull-large y.
```

The most typical programmatic use case I would think would be to pull large, but not overwrite existing. So maybe I'd include a convenience mode for that:

```
-s, --static   Pull large files, no overwrite
```

thoughts?

**Comment by stolarczyk** [comment]
>  So you'd have to force, and then turn off some aspect of it?

yes, that was the idea. But if that's confusing we can go with one of your suggestions. I like the first one more. 

Adding `--static` is  a good thought

**Comment by nsheff** [comment]
in fact I don't see any use really for `--force` alone... seems like a much less frequent use case. and you can always just use both flags. 

I don't htink `static` is a good name, though.

**Comment by stolarczyk** [comment]
> I don't htink static is a good name, though.

maybe `--batch` for batch mode?

**Comment by nsheff** [comment]
> maybe --batch for batch mode?

yeah, that's better than static! could do `--sync` along the same vein

**Comment by nsheff** [comment]
I think batch is the best one.

**Comment by stolarczyk** [comment]
```
[mstolarczyk@MichalsMBP r]: refgenie pull -h
usage: refgenie pull [-h] [-c GENOME_CONFIG] [-g GENOME]
                     [--no-overwrite | --force-overwrite]
                     [--no-large | --pull-large] [-b]
                     asset-registry-paths [asset-registry-paths ...]

Download assets.

positional arguments:
  asset-registry-paths  One or more registry path strings that identify assets
                        (e.g. hg38/fasta or hg38/fasta:tag).

optional arguments:
  -h, --help            show this help message and exit
  -c GENOME_CONFIG, --genome-config GENOME_CONFIG
                        Path to local genome configuration file. Optional if
                        REFGENIE environment variable is set.
  -g GENOME, --genome GENOME
                        Reference assembly ID, e.g. mm10.

Prompt handling:
  These flags configure the pull prompt responses.

  --no-overwrite        Do not overwrite if asset exists.
  --force-overwrite     Overwrite if asset exists.
  --no-large            Do not pull archives over 5GB.
  --pull-large          Pull any archive, regardless of its size.
  -b, --batch           Use batch mode: pull large archives, do no overwrite
```

ok so that's what we ended up with. The opposing flags are mutually exclusive.

**Comment by nsheff** [comment]
Ok I'm satisfied with that. Last thought -- make the large archives flag at 10Gb instead of 5Gb? Many assets are 5-10Gb.

**Comment by stolarczyk** [comment]
Or better yet, we can make it configurable, for example via `--size-cutoff <x>` (in gigabytes) with 10 as the default value

or is this just going to clutter the help and won't be used?

**Comment by nsheff** [comment]
I like that.  Not sure if it's overkill, but it makes it really configurable! What if some refgenie server instance has a bunch of assets and then 1 asset that's 70Gb. This way, you could say `--size-cutoff 50G` and it would just skip the one huge one.

would you want it to take '10' or '10G' or '500M'? the advantage is you could say `-cutoff 20M` to get just the small stuff, for example, for testing.

**Comment by stolarczyk** [comment]
> you could say -cutoff 20M to get just the small stuff, for example, for testing.

that's a great use case! I did not think of that

> would you want it to take '10' or '10G' or '500M'?

I would prefer this to be a float with no unit, interpreted as gigabytes since this is what needs to be passed to the decision making function and, honestly, this feels easier to use. There would be no confusion regarding the unit format: Mb, MB, mb, M

**Comment by nsheff** [comment]
ok, agreed.

**Comment by stolarczyk** [comment]
ok, done:

```
[mstolarczyk@MichalsMBP r]: refgenie pull -c g.yaml rCRSd/fasta --size-cutoff 0.001 
This archive exceeds the size cutoff (8.6KB > 0.001GB). Do you want to proceed? [y/N] N
Skipping pull of rCRSd/fasta:default; size: 8.6KB

[mstolarczyk@MichalsMBP r]: refgenie pull -c g.yaml hg18/star_index 
This archive exceeds the size cutoff (23.9GB > 10GB). Do you want to proceed? [y/N] N
Skipping pull of hg18/star_index:default; size: 23.9GB

[mstolarczyk@MichalsMBP r]: refgenie pull -c g.yaml hg18/star_index --size-cutoff 25
Downloading URL: http://rg.databio.org:82/v2/asset/hg18/star_index/archive
hg18/star_index:default  0%|▎ 
```
