### ISSUE TITLE
Config file upgrade utility

### ISSUE THREAD

**Issue by nsheff** [refgenie/refgenie#203]
We've briefly discussed but I wanted to re-open this conversation topic.

The currently released config version is 0.3. The development version is 0.4. Do we need to provide an automatic upgrade? The big difference is that version 0.4, genomes are now indexed by digest rather than human-readable identifier.

It should be possible to write an 'upgrader' script that would handle this, perhaps integrated into a refgenie release. A few reasons that might be worth it:

- if someone has been using refgenie in their work, it will suddenly stop working when we release the new refgenieserver, with no apparent way to fix things other than starting over. this will not be good for users
- we are going to face additional config 'upgrades' like this -- for instance, when we switch from refgenie genome digests to GA4GH digests (once that spec is finalized). We'll have to upgrade again.

Given these things, maybe it makes sense to some basic infrastructure for upgrading a config file. the refgenconf object would have an 'upgrade' function, which operates on a 0.3 and converts it to 0.4. perhaps it uses a server to do this, retrieving the checksums from the server, so it doesn't have to recompute them? at least where possible.

Given that refgenie has started to be adopted and used in practice, I now think it's important to provide this upgrade capability, so that users can seamlessly use refgenie even as we upgrade, and not require a rebuild every time something changes.

**Comment by xuebingjie1990** [comment]
I was able to create an 'upgrade' function that converts the 0.3 config to the 0.4 config.  But some functions, like ``` refgenie seek```, are still affected because the ```genome_folder``` structure is different between the current released version and the dev version.  Should the 'upgrade' function also take care of this issue?

**Comment by stolarczyk** [comment]
> Should the 'upgrade' function also take care of this issue?

yes, I think that upgrading just the config would be pointless. Renaming the directories and all the asset files is the most cumbersome and hard part for manual version upgrade. 

I've already built some infrastructure that will help:

https://github.com/refgenie/refgenconf/blob/d9d64246953850123e036fc13abaff41a137a826/refgenconf/refgenconf.py#L2091-L2113

So with this, the process should  be relatively easy:

1. Remove `alias` dir
2. Move contents of `data` dir up one level
3. Run `_swap_names_in_tree` on the contents from 2.

And I _think_ that's it

**Comment by nsheff** [comment]
make sure to control for the case that something fails halfway through. So make these changes in a sandbox, and then remove old stuff as a last step, or something, so you don't break things if it fails halfway through.

**Comment by stolarczyk** [comment]
related thought: isn't this process too "invasive" to be carried out automatically when the the config version is not compliant? No other refgenie command makes so many changes to the config and asset dir. Additionally, I think one might want to run `refgenie upgrade` as a separate task, after taking care of, e.g FS writability permissions or whatever. For instance, if the refgenie asset dir is writable to me and I'm in charge of maintaining it for a group of people and another user, just with write permissions, tries to call `refgenie seek` this would trigger the upgrade process that would fail right away. I would personally prefer to be presented with error saying sth like: `This genome config  is not compliant with current standards. Please call: refgenie upgrade --target-version 0.4` in the first place. What do you think?

**Comment by xuebingjie1990** [comment]
I think if it just updates the config file we can do it automatically. But if it includes changing the file structure, I think the user should have the option to either upgrade config and genome_folder or downgrade to the old refgenie depends on the individual need.  

The current ```ConfigNotCompliantError``` message is 
```This genome config (v0.3) is not compliant with v0.4 standards. To use it, please downgrade refgenie: 'pip install "refgenie>=0.7.0,<0.10.0"'``` 
 Maybe we can change to ```This genome config (v0.3) is not compliant with v0.4 standards. Do you want to upgrade to v0.4? (n/y)``` if y, then run ```refgenie upgrade```; if n, then raise the ```ConfigNotCompliantError```?

**Comment by xuebingjie1990** [comment]
> 1. Remove `alias` dir
> 2. Move contents of `data` dir up one level
> 3. Run `_swap_names_in_tree` on the contents from 2.

why are we removing the `alias` dir? The dev `refgenie build` creates both the `alias` and the `data`dir. The structure inside `alias` is almost identical to the genome_folder the old `refgenie build` creates (except the `__ASDs.json` file).  The contents inside `data` are similar but use the digest as the file names instead of the alias.  

For the new version, should the`genome_folder` only has contents inside `data`?

**Comment by stolarczyk** [comment]
Sorry, the instructions I listed were for the config version _downgrade_ which is wrong, obviously... 

You need to create the data and alias directories and rename the files in the data directory to include digest names instead of genome names. Additionally, create the symlinks in alias directories.

The alias creation is already implemented in refgenconf so you'll probably just need abstract this away and reuse.

**Comment by xuebingjie1990** [comment]
> Sorry, the instructions I listed were for the config version _downgrade_ which is wrong, obviously...
 That makes more sense. Thank you

**Comment by nsheff** [comment]
I agree with requriing a separate call to `refgenie upgrade` in general -- but can you imagine a situation where this is happening on a remote cron job or something and somebody wants to just set it to "always upgrade" and never have to do this manually?

Anyway, I'm fine with:

Just raise a ConfigNotCompliantError with message:
This genome config (v0.3) is not compliant with v0.4. To use it, please upgrade the config file: 'refgenie upgrade --target-version 0.4', or downgrade refgenie: 'pip install "refgenie>=0.7.0,<0.10.0"'.

For `refgenie upgrade`, prompt by default with a note that it will alter the files on disk and then make sure there's a `--force` option to skip the prompt.
