### ISSUE TITLE
Bump refgenconf requirement

### ISSUE THREAD

**Issue by nsheff** [refgenie/refgenie#207]
```
refgenie build t7/epilog_index
Traceback (most recent call last):
  File "/home/nsheff/.local/bin/refgenie", line 5, in <module>
    from refgenie.__main__ import main
  File "/home/nsheff/.local/lib/python3.8/site-packages/refgenie/__main__.py", line 1, in <module>
    from .refgenie import main
  File "/home/nsheff/.local/lib/python3.8/site-packages/refgenie/refgenie.py", line 7, in <module>
    from rich.console import Console
ModuleNotFoundError: No module named 'rich'
```

does rich need to be added to requirements somewhere?

**Comment by nsheff** [comment]
or it might just be that the refgenie requirement for refgenconf needs to be increased?

**Comment by stolarczyk** [comment]
you probably have incorrect refgenconf installed

**Comment by stolarczyk** [comment]
`refgenconf` is intentionally commented out from the `requirements-all.txt`:

https://github.com/refgenie/refgenie/blob/557e0a37863ac8b7a02e6c5d58b5da6ae8c09371/requirements/requirements-all.txt#L1-L4

the dev version is added to `requirements-dev.txt`, though:

https://github.com/refgenie/refgenie/blob/557e0a37863ac8b7a02e6c5d58b5da6ae8c09371/requirements/requirements-dev.txt#L1-L2

I'll uncomment the line, but the `-dev` appendix will need to be removed after `refgenconf` release anyway.

**Comment by nsheff** [comment]
no need for now, just something that needs to be addressed before release. I added a checkbox the to the PR
