### ISSUE TITLE
refgenie upgrade failure when fasta asset is missing and server isn't compatible

### ISSUE THREAD

**Issue by nsheff** [refgenie/refgenie#213]
I just tried to upgrade my local file and got this:

```
The following refgenieserver instances are not compatible or do not exist: ['http://refgenomes.databio.org']
Upgrading v0.3 config file format to v0.4
Genome digest for rCRSd is not available on any of the servers. Generating the digest from a local fasta file
Loaded AnnotatedSequenceDigestList (1 sequences)
Genome digest for hg19 is not available on any of the servers. Generating the digest from a local fasta file
Loaded AnnotatedSequenceDigestList (93 sequences)
Genome digest for hg38 is not available on any of the servers. Generating the digest from a local fasta file
Traceback (most recent call last):
  File "/home/nsheff/.local/lib/python3.8/site-packages/refgenconf/helpers.py", line 111, in format_config_03_04
    url_alias = get_json_url(s=server, i=API_VERSION+API_ID_ALIAS_DIGEST).format(alias=genome)
  File "/home/nsheff/.local/lib/python3.8/site-packages/refgenconf/refgenconf.py", line 2176, in <lambda>
    get_json_url=lambda s, i: s + _get_server_endpoints_mapping(s)[i],
KeyError: 'v3custom_Id_alias_digest'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nsheff/.local/bin/refgenie", line 8, in <module>
    sys.exit(main())
  File "/home/nsheff/.local/lib/python3.8/site-packages/refgenie/refgenie.py", line 944, in main
    upgrade_config(target_version=args.target_version,
  File "/home/nsheff/.local/lib/python3.8/site-packages/refgenconf/refgenconf.py", line 2240, in upgrade_config
    missing_digest = format_config(rgc, get_json_url=get_json_url)
  File "/home/nsheff/.local/lib/python3.8/site-packages/refgenconf/helpers.py", line 125, in format_config_03_04
    digest, _ = ssc.load_fasta(asset_path)
  File "/home/nsheff/.local/lib/python3.8/site-packages/refgenconf/seqcol.py", line 118, in load_fasta
    with openfun(fa_file, 'rt') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/nsheff/code/refgenie_sandbox/hg38/fasta/default/hg38.fa'
nsheff@zither:~/code/refgenie$ ll /home/nsheff/code/refgenie_sandbox/hg38/fasta/default/
```

I believe this is because I lack the local fasta asset for this genome, for which I have some other assets. This case needs to be handled. 

I was using the latest version of dev_config_upgrade of both refgenie and refgenconf. Did I forget to update something?

**Comment by nsheff** [comment]
interesting, I think I did have the fasta asset in the config, but the file was missing.

So you may be checking for the asset to be present, but you should also confirm that the fasta file is actually there on disk. it *should* be, but if something is messed up.... So, small issue, but still we should catch this.

**Comment by xuebingjie1990** [comment]
should we use fasta file under other tags if the default one is missing the actual file? right now it only checks if there is a default fasta asset.

**Comment by nsheff** [comment]
good question. in fact each tag should have its own checksum, right?  tags for fasta files would in fact represent differnet genomes.

we've thought about this in quite some depth in the past @stolarczyk

**Comment by stolarczyk** [comment]
> should we use fasta file under other tags if the default one is missing the actual file?

No, use only `fasta` asset that `default_tag` points at.

> good question. in fact each tag should have its own checksum, right? tags for fasta files would in fact represent differnet genomes.

yes, ideally there should be only one fasta asset tag per genome. Multiple fasta assets + use of non-default ones to build child assets would lead to some issues in the current system.

> we've thought about this in quite some depth in the past @stolarczyk

Right, we didn't solve it yet since, _I think_, we decided to wait for the recipe system revamp (#153) which will include asset classes and probably solution to this problem

**Comment by stolarczyk** [comment]
we could potentially disallow custom fasta tags specifications for `refgenie build` to enforce within-genome identity.

**Comment by nsheff** [comment]
I think for now, just assume fasta is default. disallowing sounds fine but let's not bother since we're going revamp things soon anyway as you mention.

**Comment by xuebingjie1990** [comment]
> I think for now, just assume fasta is default. 

should we close this issue then?

**Comment by stolarczyk** [comment]
I've just linked it to the upgrade cfg PR, it will be closed once we confirm it worked and merge
