### ISSUE TITLE
Adding an automatic `dir` seek key

### ISSUE THREAD

**Issue by nsheff** [refgenie/refgenie#217]
Originally, the bowtie2 path pointed to the directory, and then we changed it to point to the prefix actually consumed by bowtie2.

Now I'm finding in CWL I need the path to the directory again: https://cwl.discourse.group/t/can-you-convert-an-input-string-into-a-file-or-directory-input/218

So, we could just add a directory seek key (maybe `bowtie2.dir`?) to the recipe so you can get at that with a specific seek key. But then it struck me that maybe this should just be a universal built in : the `.dir` seek key could be a special  case that just always points to the asset's directory. Then it would never have to be specified in a recipe and would just always work.

Not sure if this is a good idea. Just brainstorming here.

**Comment by stolarczyk** [comment]
FWIW, there is already a way to do this in `RefGenConf.seek` if you set `enclosing_dir=False`. 

Maybe we could add  this to the CLI? `refgenie seek --enclosing-dir`?

**Comment by nsheff** [comment]
I see. Well, in this case, I actually need to be able to specify this at the time of specifying registry path... so it's actually neither in a `refgenie seek` call, nor in a `rgc.seek()` call... it would be a pipeline author writing `refgenie://hg19/bowtie2_index` -- how can this person specify it?

Enabling `refgenie://hg19/bowtie2_index.dir` would solve that, but it has to be via a seek key

**Comment by stolarczyk** [comment]
Ok, it seems like seek key is the way to go then. 
Do you think it's a seek key explicitly defined in the recipe (enforced by recipe schema, so it always has to be there) or added automatically to every asset within refgenie?

I think I'd prefer this to be defined in the recipe for 2 reasons: 1) Flexibility: maybe this will not always be the same, enclosing dir, 2) Explicitness

**Comment by nsheff** [comment]
Ok, in that case we don't need to change anything. I just have to add the 'dir' seek key to the bowtie 2 inde -- and in fact I did this in my test case and it works. But this issue was proposing to make it universal somehow so that all assets would have the ability inherently. 

About Flexibility -- what do you mean? In fact it would always be the same -- it's just the enclosing dir of the asset, the `{asset_outfolder}` referred to in the recipe. There's always one of these for any recipe. So making it automatic does have something going for it: 1) Consistency: so a user knows they can always do `.dir` (or whatever) and get that parent `{asset_folder}`. You're right about explicitness though, what I'm proposing would be a magic extra thing that's not part of the recipe.

You're right that for many assets, this is in fact the default seek key already. But for ones that aren't, it might be useful to have a blanket way to always get the asset folder. 

For bowtie2 I just make the ASSET section in recipe like so:

```
        ASSETS: {
            "bowtie2_index": "{genome}"
        },
```
becomes:
```
        ASSETS: {
            "bowtie2_index": "{genome}",
            dir: "."
        },
```

But now, do we want to add this capability for every other recipe that doesn't specify the folder already? In fact it's only a few right now for which this may be useful -- the ones that would fall into this category are: bwa index, and tallymer index. I think most others are either: 1) already pointing at the directory with the default seek key, or 2) only have 1 file in the asset anyway, so it's unlikely to be useful to point to the directory.

**Comment by nsheff** [comment]
Probably could be solved as part of #198

**Comment by stolarczyk** [comment]
Should we implement this now, as a part of [cloud links milestone](https://github.com/refgenie/refgenie/milestone/8) or wait for the [recipe system revamp](https://github.com/refgenie/refgenie/milestone/6)?

**Comment by nsheff** [comment]
Let's just do it now; I don't think it needs to be tied to the recipe system revamp.

**Comment by stolarczyk** [comment]
ok, so in the most basic case it's as simple as `dict.update({"dir": "."})`. 

But what about edge cases? Do we disallow using `dir` seek_key in the recipes with a schema (I created one some time ago: https://github.com/refgenie/refgenie/blob/master/refgenie/schemas/recipe_schema.yaml)? Or just override the potentially defined `dir` seek key?

**Comment by stolarczyk** [comment]
> But what about edge cases? Do we disallow using dir seek_key in the recipes with a schema

That's what I did, the other option might lead to confusion, I think.

**Comment by nsheff** [comment]
@stolarczyk when was the .dir seek key added? it's not documented in the changelog, and doesn't work in v 0.11.0

```
efgenie seek hg38/bowtie2_index.dir
Traceback (most recent call last):
  File "/home/nsheff/.local/lib/python3.8/site-packages/attmap/ordattmap.py", line 46, in __getitem__
    return super(OrdAttMap, self).__getitem__(item)
KeyError: 'dir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nsheff/.local/lib/python3.8/site-packages/refgenconf/refgenconf.py", line 747, in seek
    seek_val = asset_tag_data[CFG_SEEK_KEYS_KEY][seek_key]
  File "/home/nsheff/.local/lib/python3.8/site-packages/attmap/pathex_attmap.py", line 59, in __getitem__
    v = super(PathExAttMap, self).__getitem__(item)
  File "/home/nsheff/.local/lib/python3.8/site-packages/attmap/ordattmap.py", line 48, in __getitem__
    return AttMap.__getitem__(self, item)
  File "/home/nsheff/.local/lib/python3.8/site-packages/attmap/attmap.py", line 32, in __getitem__
    return self.__dict__[item]
KeyError: 'dir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nsheff/.local/bin/refgenie", line 8, in <module>
    sys.exit(main())
  File "/home/nsheff/.local/lib/python3.8/site-packages/refgenie/cli.py", line 162, in main
    rgc.seek(
  File "/home/nsheff/.local/lib/python3.8/site-packages/refgenconf/refgenconf.py", line 749, in seek
    raise MissingSeekKeyError(
refgenconf.exceptions.MissingSeekKeyError: Seek key 'dir' not defined for: 'hg38.bowtie2_index:default'
```

**Comment by stolarczyk** [comment]
It was added in 0.11.0, I think.

Maybe the asset you're `seek`ing simply doesn't consist of `dir` seek key?

**Comment by nsheff** [comment]
Can you explain what you mean? I thought the point of this is that all assets have an *automatic* `.dir` seek key?

**Comment by stolarczyk** [comment]
All assets that are built with refgenie > 0.11.0 have a `.dir` seek key added automatically, so it's automatic in this sense. Thanks to that we have the seek keys listed in `list`, `listr` and on the asset pages on the server at no cost.

Asset seeking did not change at all with regard to that. We could add a patch to `RefGenConf.seek` so that it's compatible with old assets.

**Comment by nsheff** [comment]
ah, that makes sense. so probably re-pulling the asset would fix it.

**Comment by stolarczyk** [comment]
yes, re-pulling or re-building will help. Or just manually add `dir: .` in `seek_keys` section ;)
