### ISSUE TITLE
Question about genomes not available in ensembl

### ISSUE THREAD

**Issue by josruirod** [refgenie/refgenie#218]
Hi and thanks for the software.
I'm currently dealing with some protist genomes that are not present in ensembl. I see that some assets are particularly prepared to be built from gzipped ensembl files, and I've been able to build these manually gzipping the files. 
But I wanted to ask if there are any other options to build assets such as refgene_anno without the files from refgene.

Thanks

**Comment by stolarczyk** [comment]
hi @josruirod,

refgenie recipes rely on strictly defined inputs format. For `fasta` assets it's a gzipped FASTA file and it has to follow the FASTA format spec. For `refgene_anno` the it's the "gzipped RefGene database annotation file", so if you reproduce this format with the data from other sources it will work. 

Here's the [input file](http://big.databio.org/refgenie_raw/files.hg38.refgene_anno.refgene) we used to build the `hg38/refgene_anno` asset, for example.

**Comment by stolarczyk** [comment]
keep in mind that the file I linked is gzipped, so retrieve it this way, for example:

```
wget -O hg38.refgene_anno.gz http://big.databio.org/refgenie_raw/files.hg38.refgene_anno.refgene
```

**Comment by josruirod** [comment]
Ok, thanks, I'll try to reproduce the format specs

**Comment by josruirod** [comment]
Hi, I'm currntly trying to reproduce the file you provided, the refGene. Can you point to any place where I can find the meaning of each column so I can try and reproduce from a non-model referenge genome? 
Thanks

**Comment by stolarczyk** [comment]
I'm not sure what is the meaning of the columns either. Maybe @jpsmith5, the author of the recipe will be able to help you?

**Comment by jpsmith5** [comment]
Sure thing. The schema for that refGene file is as so:

|     field    |            example           |              SQL type              |  info  |                    description                    |
|:------------:|:----------------------------:|:----------------------------------:|:------:|:-------------------------------------------------:|
| bin          | 587                          | smallint(5) unsigned               | range  | Indexing field to speed chromosome range queries. |
| name         | NM_001034679                 | varchar(255)                       | values | Name of gene (usually transcript_id from GTF)     |
| chrom        | chr1                         | varchar(255)                       | values | Reference sequence chromosome or scaffold         |
| strand       | +                            | char(1)                            | values | + or - for strand                                 |
| txStart      | 327876                       | int(10) unsigned                   | range  | Transcription start position                      |
| txEnd        | 339078                       | int(10) unsigned                   | range  | Transcription end position                        |
| cdsStart     | 327956                       | int(10) unsigned                   | range  | Coding region start                               |
| cdsEnd       | 337478                       | int(10) unsigned                   | range  | Coding region end                                 |
| exonCount    | 4                            | int(10) unsigned                   | range  | Number of exons                                   |
| exonStarts   | 327876,331232,333962,337305, | longblob                           |        | Exon start positions                              |
| exonEnds     | 328043,331406,334122,339078, | longblob                           |        | Exon end positions                                |
| score        | 0                            | int(11)                            | range  |                                                   |
| name2        | RCAN1                        | varchar(255)                       | values | Alternate name (e.g. gene_id from GTF)            |
| cdsStartStat | cmpl                         | enum('none','unk','incmpl','cmpl') | values | enum('none','unk','incmpl','cmpl')                |
| cdsEndStat   | cmpl                         | enum('none','unk','incmpl','cmpl') | values | enum('none','unk','incmpl','cmpl')                |
| exonFrames   | 0,0,0,1,                     | longblob                           |        | Exon frame {0,1,2}, or -1 if no frame for exon    |

**Comment by josruirod** [comment]
Great thanks for the help
