### ISSUE TITLE
Refgenie CLI test by hand

### ISSUE THREAD

**Issue by xuebingjie1990** [refgenie/refgenie#225]
I tested the Refgenie CLI locally, and only ran into one issue with `refgenie listr`:
1. when there are multiple server subscribed and the compatible server is not the first one in the list, I got
```
$ refgenie listr
/home/bx2ur/Documents/Testing/refgenie/genome_config.yaml
'http://refgenomes.databio.org' is not a compatible refgenieserver instance. Could not determine API endpoint defined by ID: 'v3custom_Id_genomes_dict'
```

There is one more issues when I try to test on Rivanna with the lab config (`/project/shefflab/rivanna_config/refgenie_v04.yaml`):

2. when I try to pull a asset that is available on the server, I got:
```
$ refgenie pull rCRSd/fasta
'rCRSd/fasta:default' not available on any of the following servers: http://rg.databio.org
```
Maybe because ` rCRSd/fasta` already exist locally. 

Also, because the digests are different now, when should we rerun the upgrade again?

**Comment by stolarczyk** [comment]
thanks for testing

For 1., I noticed the issue yesterday, if the first server is invalid it stops instead of checking others, but I think it does for `pull`. This should be easy to fix. You can try to resolve this if you want.

For 2., I'm not sure what is going on.. will need to investigate

> Also, because the digests are different now, when should we rerun the upgrade again?

Once I re-build and re-archive the assets to be served with the production instance of refgenieserver

**Comment by xuebingjie1990** [comment]
> For 1., I noticed the issue yesterday, if the first server is invalid it stops instead of checking others, but I think it does for `pull`. This should be easy to fix. You can try to resolve this if you want.

I think the `pull` also has this issue:

here is when I try to pull a fasta asset:
```$ refgenie pull human_repeats/fasta
No local digest for genome alias: human_repeats
'http://refgenomes.databio.org' is not a compatible refgenieserver instance. Could not determine API endpoint defined by ID: 'v3custom_Id_alias_digest'
```
here is when I try to pull another asset when the fasta asset already exsit:
```
$ refgenie pull hg38/bowtie2_index
'http://refgenomes.databio.org' is not a compatible refgenieserver instance. Could not determine API endpoint defined by ID: 'v3custom_Id_default_tag'
```

(I tested `pull` on a new genome config I initiated, not the lab config)

I'll try to fix this problem.

**Comment by xuebingjie1990** [comment]
> Once I re-build and re-archive the assets to be served with the production instance of refgenieserver

I think this issue is fixed.  let me know if your are ready for me to run upgrade again.
