### ISSUE TITLE
pull and listr behavior in multi-server context

### ISSUE THREAD

**Issue by stolarczyk** [refgenie/refgenie#226]
loop through the servers the config subscribes to and:

- `refgenie listr`: create a table for each compatible server
- `refgenie pull`: retrieve the asset from the first compatible server that the asset is available on

attempts to perform these actions on an incompatible server instance should be logged, just as it is currently implemented

**Comment by xuebingjie1990** [comment]
I commented out this line so it won't exit when it loop to a non-compatible server. 
https://github.com/refgenie/refgenconf/blob/7522fbf4a282c180ead398e610f43a169c105604/refgenconf/refgenconf.py#L3098
But I haven't test how that would affect other functions.

Now `listr` should print all compatible servers regardless of where it is in the `genome_servers`  list (relative to the non-compatible server).  But I didn't test it with more than one compatible servers.  Is http://rg.databio.org the only compatible server for now?

**Comment by xuebingjie1990** [comment]
Also, are we still using `rgc.listr` anywhere? I commented out the whole section when testing the CLI `listr`, and nothing changes. 
https://github.com/refgenie/refgenconf/blob/3e86403b79747499123adc400a380383f8a50759/refgenconf/refgenconf.py#L1030-L1055

**Comment by stolarczyk** [comment]
>  Is http://rg.databio.org the only compatible server for now?

there's also this one: http://plantref.databio.org/index but it looks like it only serves metadata. I'm usually spinning up my own, local server for testing

> Also, are we still using rgc.listr anywhere? I commented out the whole section when testing the CLI listr, and nothing changes.

Don't comment it out. It's user-facing API, we want to keep it.

**Comment by xuebingjie1990** [comment]
> there's also this one: http://plantref.databio.org/index but it looks like it only serves metadata. I'm usually spinning up my own, local server for testing

my `genome_servers` list is like this:
```
genome_servers: 
 - http://plantref.databio.org
 - http://refgenomes.databio.org
 - http://rg.databio.org
```

and both http://plantref.databio.org and  http://rg.databio.org printed out.

> Don't comment it out. It's user-facing API, we want to keep it.
It's not now.  I fixed it once I realize I commented out for testing....

**Comment by stolarczyk** [comment]
great, looks good!

so the `sys.exit(1)` wast the culprit?

**Comment by xuebingjie1990** [comment]
> so `sys.exit(1)` was the culprit?

Basically yes. There are some minor issues to work around after that line is removed.  I tested `pull`, `listr`, `subscribe`, `unsubscribe`, things I think are relate to the server; everything works fine now.
