### ISSUE TITLE
docs update?

### ISSUE THREAD

**Issue by nsheff** [refgenie/refgenie#229]
docs say: 

Build your own indexes and assets for a custom reference genome

Refgenie assets are scripted, so if what you need is not available remotely, you can use build it locally:

```
refgenie build mygenome/bwa_index --files fasta=mygenome.fa.gz
```

but I thought you couldn't do it like this anymore... don't you instead have to specify the fasta asset?

**Comment by stolarczyk** [comment]
well, I'm not sure if this has ever been possible. 

I'll scan all the documentation to eliminate things like that.
