### ISSUE TITLE
compatible refgenieserver instance

### ISSUE THREAD

**Issue by chrishuges** [refgenie/refgenie#232]
Hi,

I have just installed a new instance of Refgenie using the instructions provided [here](http://refgenie.databio.org/en/latest/install/). This is on a linux server running CentOS7. For reference, I did have a previous installation of refgenie on this machine that worked fine but it had to be wiped for unrelated reasons, so we are starting from nothing.

```
$ refgenie --version
refgenie 0.10.0 | refgenconf 0.10.0
```

Everything seems to go fine with install and initiation, but I get the error:

```
$ refgenie listr
'http://refgenomes.databio.org' is not a compatible refgenieserver instance. Could not determine API endpoint defined by ID: '_private_apicustom_Id_genomes_dict'
Could not list assets from the following servers: ['http://refgenomes.databio.org']
```

Not sure what is happening. If I try to run a pull command, it doesn't give an error and it creates the correct directory structure in my index folder, but there is nothing actually in the folders themselves.

```
$refgenie pull hg38/fasta
Compatible refgenieserver instances: ['http://refgenomes.databio.org']
No local digest for genome alias: hg38
Setting 'hg38' identity with server: http://refgenomes.databio.org/v3/genomes/genome_digest/hg38
Determined server digest for local genome alias (hg38): 2230c535660fb4774114bfa966a62f823fdb6d21acf138d4
Set genome alias (2230c535660fb4774114bfa966a62f823fdb6d21acf138d4: hg38)
Created alias directories:
 - /projects/ptx_analysis/chughes/databases/refgenieIndexes/alias/hg38
Downloading URL: http://refgenomes.databio.org/v3/assets/archive/2230c535660fb4774114bfa966a62f823fdb6d21acf138d4/fasta

```

I figure I must be missing something pretty simple. I tried rolling back to v0.9.3 and I still get a similar issue with the server instance. 

Any ideas?

Thanks,
Chris

**Comment by stolarczyk** [comment]
hi @chrishuges,

thanks for reporting

For `refgenie listr`, you've identified a bug in refgenieserver, which will be fixed today.

For `refgenie pull`, I'm not sure why it didn't download the assets from the server. Are you sure the `refgenie pull` command finished successfully? The log you pasted looks incomplete. Maybe try with a small asset to test it again, like `rCRSd/fasta:default`.

**Comment by chrishuges** [comment]
Great, thanks!

For the pull, you are correct. It seems it just wasn't finishing properly. Seems to be OK now (I have also tried it with some bigger files).

```
$ refgenie pull rCRSd/fasta:default
Compatible refgenieserver instances: ['http://refgenomes.databio.org']
No local digest for genome alias: rCRSd
Setting 'rCRSd' identity with server: http://refgenomes.databio.org/v3/genomes/genome_digest/rCRSd
Determined server digest for local genome alias (rCRSd): 94e0d21feb576e6af61cd2a798ad30682ef2428bb7eabbb4
Set genome alias (94e0d21feb576e6af61cd2a798ad30682ef2428bb7eabbb4: rCRSd)
Created alias directories:
 - /projects/ptx_analysis/chughes/databases/refgenieIndexes/alias/rCRSd
Downloading URL: http://refgenomes.databio.org/v3/assets/archive/94e0d21feb576e6af61cd2a798ad30682ef2428bb7eabbb4/fasta
94e0d21feb576e6af61cd2a798ad30682ef2428bb7eabbb4/fasta:default ━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.0% • 24.0/8.6 KB • 81.7 MB/s • 0:00:00
Download complete: /projects/ptx_analysis/chughes/databases/refgenieIndexes/data/94e0d21feb576e6af61cd2a798ad30682ef2428bb7eabbb4/fasta/fasta__default.tgz
Extracting asset tarball: /projects/ptx_analysis/chughes/databases/refgenieIndexes/data/94e0d21feb576e6af61cd2a798ad30682ef2428bb7eabbb4/fasta/fasta__default.tgz
Default tag for '94e0d21feb576e6af61cd2a798ad30682ef2428bb7eabbb4/fasta' set to: default
Initializing genome: rCRSd
Loaded AnnotatedSequenceDigestList (1 sequences)
Set genome alias (94e0d21feb576e6af61cd2a798ad30682ef2428bb7eabbb4: rCRSd)
Created alias directories:
 - /projects/ptx_analysis/chughes/databases/refgenieIndexes/alias/rCRSd/fasta/default
 ```

**Comment by stolarczyk** [comment]
the issue you had with `refgenie listr` is fixed now as well. Please close the issue once you confirm.

**Comment by chrishuges** [comment]
Works, thanks!
