### ISSUE TITLE
Populate should allow remote links

### ISSUE THREAD

**Issue by nsheff** [refgenie/refgenie#234]
would be nice if when I `refgenie populate` something, I could choose to use local links, or remote links with a specific `remoteClass`.

**Comment by stolarczyk** [comment]
done. This is how it works:

```
[mstolarczyk@MichalsMBP refgenie]: echo 'testing refgenie string: refgenie://hg38/fasta' | refgenie populate -c g.yml --remote --remote-class s3
testing refgenie string: s3://awspds.refgenie.databio.org/rg.databio.org/2230c535660fb4774114bfa966a62f823fdb6d21acf138d4/fasta__default/2230c535660fb4774114bfa966a62f823fdb6d21acf138d4.fa
```

**Comment by nsheff** [comment]
awesome. is the config required?

**Comment by stolarczyk** [comment]
yes, but I'm currently working on making it not required and realized that it's more complicated than `listr` and `seekr` since there's no dedicated `populater` command. Should we add one? There would be a nice distinction that commands/methods ending with `r` can be used with no config.

**Comment by nsheff** [comment]
I think that makes sense to me
