### ISSUE TITLE
Renaming populate

### ISSUE THREAD

**Issue by nsheff** [refgenie/refgenie#241]
I know what it means, but `refgenie populater` looks weird because it's *almost* `populator`... so it looks like a typo. It's also long to type.

What would you think of a switch to `refgenie pop` and `refgenie popr`? Or some other verb? `strep` for string replacement? 
 
Some ideas:

- `refgenie fill`/`refgenie fillr`
- `refgenie strep`/`refgenie strepr`
- `refgenie pop`/`refgenie popr`
- `refgenie sub`/`refgenie subr`

**Comment by stolarczyk** [comment]
I'm ok with switching. I like `sub` the most.

**Comment by nsheff** [comment]
Does `sub` get confused with `subscribe`? Maybe `refgenie replace`/`refgenie replacer`

I agree with you that `sub` is the best, but because we also have `subscribe`, I would I think lean toward `fill`...

**Comment by stolarczyk** [comment]
the reason I picked `sub` is:
 - I associated `pop` with popping element from a data structure, not populating
 - `fill` didn't fill right because we don't fill blank spaces with the path, we replace strings

so, `replace` is a great option, too

**Comment by nsheff** [comment]
I agree, but `replace` is also quite a bit longer than sub or pop or fill, which fit better with other short commands like seek/list.

Do still want to have both `sub` and `subscribe`? An alternative is we can change subscribe

**Comment by stolarczyk** [comment]
I think I wouldn't change existing commands, even if they are secondary, like `subscribe`. I'm also not concerned about the `replace` length, it's not much different from `compare` or `remove`, which could be used often. 

we can do `pop` if you want. The truth is, the first time someone reads the docs it's going to make sense since then

**Comment by nsheff** [comment]
I think I'd just leave it as `populate` and `populater` then. Since I think `replace` and `replacer` have the same problems. Basically I don't think the appended `r` version should be mistakable for a word, like `replacer` or `populater`. So, `fillr`, `popr`, `subr` all work better.

**Comment by nsheff** [comment]
What is the verdict here? I think I'm open to `popr`, or `subr` or `populater`. So, maybe just leave it at `populatr` since it's already implemented that way?

**Comment by stolarczyk** [comment]
I just left it as `populater`

**Comment by nsheff** [comment]
alright sounds good.
