### ISSUE TITLE
refgenie populate question

### ISSUE THREAD

**Issue by nsheff** [refgenie/refgenie#247]
These docs look really nice: http://refgenie.databio.org/en/latest/remote/

But it looks like the `populate`/`populater` functions can only return the `http` remote class. Is there a way to specify to `populate` that you want the s3 remote class? If so, can we add that to the docs?

**Comment by stolarczyk** [comment]
Specifying remote classes is supported. The example of `populater` in that page, uses this feature (note the `-r` option)

Also, check out the "populate text from standard input" section, there is a sentence that hints at that:

> -r/--remote-class command specifies the data provider link to be used in the output. Please refer to the refgenieserver instance API endpoint that lists available options, for example: http://rg.databio.org/remotes/dict.

To make it less confusing we could mention this feature at the top, in "Commands available in remote mode" section.

**Comment by nsheff** [comment]
Not sure how I missed that, it was in there! I think it was just the formatting and the way it was presented. I tried to clarify it. thanks.
