### ISSUE TITLE
'refgenie add' documentation is missing (404)

### ISSUE THREAD

**Issue by ttriche** [refgenie/refgenie#249]
http://refgenie.databio.org/en/latest/faq/

"All you need to do is write your assets into your genome configuration file, which is easy using [refgenie add](http://refgenie.databio.org/en/latest/faq/custom_assets)"

Alas, upon visiting http://refgenie.databio.org/en/latest/faq/custom_assets ,

        \          SORRY            /
         \                         /
          \    This page does     /
           ]   not exist yet.    [    ,'|

**Comment by nsheff** [comment]
Thanks, will fix

http://refgenie.databio.org/en/latest/custom_assets/

**Comment by nsheff** [comment]
fixed.
