### ISSUE TITLE
refgenie build returns 0 even with failure

### ISSUE THREAD

**Issue by pinin4fjords** [refgenie/refgenie#258]
Currently, refgenie still return a 0 status code, even if one of the internal processes fails, such as in this example where the Samtools command failed:

[stdout.txt](https://github.com/refgenie/refgenie/files/6672689/stdout.txt)

Could there be a fix to return non-0 in such cases, to facilitate the catching of errors in workflow systems?

**Comment by nsheff** [comment]
we should definitely do this.

**Comment by nsheff** [comment]
In my hands that commit worked and now returns 1 instead of 0 if the build pipeline fails, for my test case. Not extensively tested but it seems to work...

**Comment by pinin4fjords** [comment]
Quick work- thank you

**Comment by pinin4fjords** [comment]
Unfortunately I don't think this is addressed, I'm getting the same results after doing the pip install from dev. The command was:

```
refgenie --verbosity 5 build fasciola_hepatica--Fasciola_10x_pilon/fasta:genome --files fasta=fasciola_hepatica.PRJEB25283.WBPS15.genomic.fa.gz -c /path/to/genome_config.yaml -R --map
```

You can find that fasta at ftp://ftp.ebi.ac.uk/pub/databases/wormbase/parasite/releases/WBPS15/species/fasciola_hepatica/PRJEB25283/fasciola_hepatica.PRJEB25283.WBPS15.genomic.fa.gz
