### ISSUE TITLE
Refgenie and kraken databases

### ISSUE THREAD

**Issue by victor5lm** [refgenie/refgenie#286]
In our group, we believe refgenie could be quite useful for a better management of our reference resources, and we are evaluating how to implement this tool in our lab. For some of the tasks that we carry out daily, we rely on some [minikraken](https://ccb.jhu.edu/software/kraken/) and [kraken2](https://benlangmead.github.io/aws-indexes/k2) databases, which however contain data from several microorganisms in one file.

Since refgenie organizes reference files in relation to specific assemblies (each assembly is an alias and therefore all files have to be associated with an assembly), which could be the best strategy to add these kraken databases to our refgenie config file in order for us to access different versions of these databases? Thanks a lot!

**Comment by nsheff** [comment]
hi victor, were you able to figure out how to do this?
