### ISSUE TITLE
collection-level digests

### ISSUE THREAD

**Issue by nsheff** [refgenie/refgenie#82]
For #81 we will need collection-level checksums. I think the refget v2.0 is working on this as well but I just wanted to record some ideas here:

We could just take the md5 of the fasta file. This I call the 1-layer approach because we just checksum once. Disadvantage: could different line endings  make identical sequences have different checksums? How about we first use the current refget protocol for individual sequences, and then put these into a particular format, and then checksum that. We could format like so:

chr1:64821b23d7a3c6bf42b697de48898110;chr2:d41d8cd98f00b204e9800998ecf8427e;chr3:44b2211617d4d19cc60db763ae2db74a;

Checksum that to give the collection-level checksum. The advantage of the 2-layer approach, where we transform the individual sequence checksums instead of the checksums themselves, is that we could retrieve just a list of chromosomes, then rely on existing functionality to grab the sequences themselves (if needed). This is a less expensive request in the case that we just need the list, and don't need to pull all the sequences. In fact, with this system, the lookup could become a recursive function, because we can consider the above list of checksums as a sequence of characters. If we just make refget recurse, then collections fit right in, and even collections of collections could have checksums.

Another advantage: Image we have 2 different assemblies, one of which is a subset of the other. these will have different checksums. But at the sequence level, one contains the other (the chromosomes all match). When given a checksum to look up a genome, we could retrieve just the list of chrom checksums and check for identity at this level. Not sure how useful this would be though.

**Comment by mikelove** [comment]
I've been on GA4GH calls for a year now, and the leading plan is that sequence collection checksums would be a hash function applied to lexicographic sorted hashes of individual sequences. But when I asked for more specific details, e.g. "concatenate with empty string?", or exactly how the sorting will be done, that level of detail has not been decided yet. The current leading candidate for the hash function is a truncated version of SHA-512.

Currently, `salmon index` hashes the cDNA alone of the reference transcripts (stripping off the headers, and keeping the order that they appear in the file from the reference source). And this is the identifier used by `tximeta` to identify the transcriptome.

**Comment by andrewyatz** [comment]
As @mikelove says here, this is the current level of thinking but not progressed much further than that

**Comment by nsheff** [comment]
I just implemented a first draft of collection-level checksums for refgenie in ca0127934fcbf873f927c6d58204052361e10a29 (essentially the algorithm described above).

I think preserving original order is critical because two genomes with the same chromosomes but different order will behave differently in downstream software (*eg* sequence alignment).
